name: Node Checkout Install Dependencies
description: Action to checkout a Nodejs project and install dependencies
inputs:
  node:
    description: Node version
    required: false
    default: "16"
  auth-token:
    description: Node Auth token
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node }}
        registry-url: "https://npm.pkg.github.com"
        scope: "@beezlabs-org"

    - name: Install Dependencies
      env:
        NODE_AUTH_TOKEN: ${{ inputs.auth-token }}
      run: |
        npm ci
      shell: bash
